version: "3.9"

services:
  db:
    image: postgres:13.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "pagination"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
